import type { User, Task } from './types';
import { addDays, subDays } from 'date-fns';

export const USERS: User[] = [
  { id: '1', name: 'Admin User', email: 'admin@example.com', avatar: 'https://picsum.photos/seed/1/100/100', role: 'Admin' },
  { id: '2', name: 'Manager Mike', email: 'manager@example.com', avatar: 'https://picsum.photos/seed/2/100/100', role: 'Manager' },
  { id: '3', name: 'Employee Emma', email: 'employee@example.com', avatar: 'https://picsum.photos/seed/3/100/100', role: 'Employee' },
  { id: '4', name: 'Developer Dave', email: 'dave@example.com', avatar: 'https://picsum.photos/seed/4/100/100', role: 'Employee' },
  { id: '5', name: 'Designer Diana', email: 'diana@example.com', avatar: 'https://picsum.photos/seed/5/100/100', role: 'Employee' },
];

const [admin, manager, emma, dave, diana] = USERS;

export const TASKS: Task[] = [
  {
    id: 'TASK-1',
    title: 'Design the new dashboard layout',
    description: 'Create mockups and prototypes for the new dashboard design, focusing on user experience.',
    status: 'In Progress',
    priority: 'High',
    deadline: addDays(new Date(), 7),
    createdAt: subDays(new Date(), 2),
    assigner: manager,
    assignee: diana,
    tags: ['design', 'ui', 'ux'],
    recurrence: 'None',
  },
  {
    id: 'TASK-2',
    title: 'Develop the authentication feature',
    description: 'Implement JWT-based authentication for the application.',
    status: 'To Do',
    priority: 'Urgent',
    deadline: addDays(new Date(), 5),
    createdAt: subDays(new Date(), 1),
    assigner: manager,
    assignee: dave,
    tags: ['development', 'backend', 'security'],
    recurrence: 'None',
  },
  {
    id: 'TASK-3',
    title: 'Write API documentation',
    description: 'Document all the public API endpoints using Swagger/OpenAPI.',
    status: 'To Do',
    priority: 'Medium',
    deadline: addDays(new Date(), 14),
    createdAt: new Date(),
    assigner: manager,
    assignee: emma,
    tags: ['documentation', 'api'],
    recurrence: 'None',
  },
  {
    id: 'TASK-4',
    title: 'Review quarterly budget',
    description: 'Analyze the quarterly spending and prepare a report for the board meeting.',
    status: 'Done',
    priority: 'High',
    deadline: subDays(new Date(), 3),
    createdAt: subDays(new Date(), 10),
    assigner: admin,
    assignee: manager,
    tags: ['finance', 'report'],
    recurrence: 'None',
  },
  {
    id: 'TASK-5',
    title: 'Fix login page CSS bug',
    description: 'The login button is misaligned on mobile devices. This needs to be fixed.',
    status: 'In Progress',
    priority: 'Medium',
    deadline: addDays(new Date(), 1),
    createdAt: subDays(new Date(), 1),
    assigner: manager,
    assignee: dave,
    tags: ['bug', 'css', 'frontend'],
    recurrence: 'None',
  },
  {
    id: 'TASK-6',
    title: 'Plan the next marketing campaign',
    description: 'Brainstorm ideas for the upcoming Q3 marketing campaign.',
    status: 'To Do',
    priority: 'Low',
    deadline: addDays(new Date(), 30),
    createdAt: new Date(),
    assigner: manager,
    assignee: emma,
    tags: ['marketing', 'planning'],
    recurrence: 'None',
  },
  {
    id: 'TASK-7',
    title: 'User testing for the new feature',
    description: 'Conduct user testing sessions with a focus group to get feedback on the new reporting feature.',
    status: 'To Do',
    priority: 'High',
    deadline: addDays(new Date(), 10),
    createdAt: subDays(new Date(), 3),
    assigner: manager,
    assignee: diana,
    tags: ['testing', 'ux'],
    recurrence: 'None',
  },
  {
    id: 'TASK-8',
    title: 'Deploy server updates',
    description: 'Deploy the latest security patches and updates to the production server.',
    status: 'Cancelled',
    priority: 'Urgent',
    deadline: subDays(new Date(), 1),
    createdAt: subDays(new Date(), 2),
    assigner: admin,
    assignee: dave,
    tags: ['deployment', 'server'],
    recurrence: 'None',
  },
  {
    id: 'TASK-9',
    title: 'Weekly team sync meeting',
    description: 'Regular weekly sync to discuss progress and blockers.',
    status: 'Done',
    priority: 'Medium',
    deadline: subDays(new Date(), 4),
    createdAt: subDays(new Date(), 4),
    assigner: manager,
    assignee: manager,
    recurrence: 'Weekly',
  },
  {
    id: 'TASK-10',
    title: 'Onboard new employee',
    description: 'Prepare onboarding materials and schedule introduction meetings for the new hire.',
    status: 'To Do',
    priority: 'High',
    deadline: addDays(new Date(), 3),
    createdAt: new Date(),
    assigner: manager,
    assignee: manager,
    tags: ['hr', 'onboarding'],
    recurrence: 'None',
  },
];
